[package]
name = "ocr_imagemagick"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "ocr_imagemagick"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.22.0"
magick_rust = "0.17.0"